version: "3.4"
services:
  db:
    container_name: postgres_db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: abdelkaderlounis98@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
